name: CI Workflow

on:
  push:
    branches:
      - main
      - devops
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0
          
      - name: Clone Project
        run: git clone https://github.com/vova4211/dofd-05-dotnet-vova4211.git

      - name: Navigate to Project Directory
        run: cd dofd-05-dotnet-vova4211
        
      - name: Show .NET SDKs
        run: dotnet --list-sdks

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: devops

      - name: Restore Dependencies
        run: dotnet restore
          
      - name: Build Project
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --configuration Release
        
